package dao;

import exceptions.ModelDaoReadException;
import exceptions.ModelioException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import sudoku.SudokuBoard;
import sudoku.solver.BacktrackingSudokuSolver;

public class JdbcSudokuBoardDao implements Dao<SudokuBoard> {
    private Statement statement;
    private String boardName;
    private SudokuBoard initialBoard;

    public JdbcSudokuBoardDao(String dbname) {
        createDatabase(dbname);
    }

    private void createDatabase(String dbname) {
        try {
            String urlConnection = "jdbc:derby:./target/" + dbname + ";create=true";
            Connection con = DriverManager.getConnection(urlConnection);
            statement = con.createStatement();
        } catch (SQLException e) {
            return;
        }
        try {
            statement.execute("CREATE TABLE boards "
                    + "(id INT PRIMARY KEY GENERATED BY DEFAULT "
                    + "AS IDENTITY (START WITH 1, INCREMENT BY 1)"
                    + ",boardName VARCHAR(255))");
        } catch (SQLException e) {
            return;
        }
        try {
            statement.execute("CREATE TABLE fields "
                    + "(id INT PRIMARY KEY GENERATED BY DEFAULT "
                    + "AS IDENTITY (START WITH 1, INCREMENT BY 1),"
                    + "boardId INT REFERENCES boards(id),x INT,y INT,fvalue INT,disabled BOOLEAN)");
        } catch (SQLException e) {
            return;
        }
    }

    public List<SudokuBoard> read(String boardName) {
        this.boardName = boardName;
        ArrayList<SudokuBoard> list = new ArrayList<>();
        list.add(read());
        list.add(this.initialBoard);
        return list;
    }

    /**
     * Read T object from file.
     *
     * @return T
     */
    @Override
    public SudokuBoard read() {
        try {
            SudokuBoard databaseBoard = new SudokuBoard(new BacktrackingSudokuSolver());
            ResultSet rs = statement.executeQuery("SELECT * FROM boards "
                    + "WHERE boardName='" + this.boardName + "'");
            if (rs.next()) {
                String id = rs.getString("id");
                ResultSet rs2 = statement.executeQuery("SELECT * FROM fields "
                        + "WHERE boardId=" + id);
                while (rs2.next()) {
                    databaseBoard.set(Integer.parseInt(rs2.getString("x")),
                            Integer.parseInt(rs2.getString("y")),
                            Integer.parseInt(rs2.getString("fvalue")));
                    if (Boolean.getBoolean(rs2.getString("disabled"))) {
                        this.initialBoard.set(Integer.parseInt(rs2.getString("x")),
                                Integer.parseInt(rs2.getString("y")),
                                Integer.parseInt(rs2.getString("fvalue")));
                    }
                }
            }
            return databaseBoard;
        } catch (SQLException e) {
            throw new ModelDaoReadException("Cannot read from database", e);
        }
    }

    public void write(SudokuBoard current, SudokuBoard initial, String boardName) {
        this.boardName = boardName;
        this.initialBoard = initial;
        write(current);
    }

    /**
     * Write (save) T object to file.
     *
     * @param obj object type T which should be saved to file
     */
    @Override
    public void write(SudokuBoard obj) {
        try {
            String id = "";
            statement.execute("INSERT INTO boards(boardName) VALUES ('" + this.boardName + "')");
            ResultSet rs = statement.executeQuery("SELECT * FROM boards "
                    + "WHERE boardName='" + this.boardName + "'");
            if (rs.next()) {
                id = rs.getString("id");
            }
            int idNum = Integer.parseInt(id);
            for (int i = 0; i < 9; i++) {
                for (int j = 0; j < 9; j++) {
                    statement.execute("INSERT INTO fields(boardId,x,y,fvalue,disabled) VALUES "
                            + "(" + idNum + "," + i + "," + j + "," + obj.get(i, j) + ","
                            + (this.initialBoard.get(i, j) == obj.get(i, j)) + ")");
                }
            }
        } catch (SQLException e) {
            throw new ModelDaoReadException("Cannot write to database", e);
        }
    }

    @Override
    public void close() throws ModelioException {

    }

    public void betterFinalize() throws Throwable {

    }
}
